[platformio]
src_dir = .

[env:teensylc]
platform = teensy
board = teensylc
framework = arduino
extra_scripts = ../../TeensyMaster/upload_with_tycmd.py
upload_protocol = custom
upload_flags = --board=8883030-Teensy
lib_deps =
	nrf24/RF24 @ 1.6.1
	adafruit/Adafruit ICM20X @ ^2.0.5
